import { AGENT_RESPONSE_SEMANTIC_VERSION, parseAgentResponse } from './agentResponse'
import type { AgentResponse, AgentResponseParseResult } from '../types/agent'
import type { DocumentFile } from '../types/document'

export type MockAgentScenario = 'message' | 'question' | 'error' | 'blueprints' | 'blueprints-invalid'

export interface MockAgentRequest {
  prompt: string
  currentDocument?: DocumentFile | null
  scenario?: MockAgentScenario
  requestId?: string
}

export async function runMockAgentProvider(request: MockAgentRequest): Promise<AgentResponseParseResult> {
  const response = createMockAgentResponse(request)
  return parseAgentResponse(response, { mainDocument: request.currentDocument ?? null })
}

export function createMockAgentResponse(request: MockAgentRequest): AgentResponse {
  const scenario = request.scenario ?? inferScenario(request.prompt)
  const base = {
    schemaVersion: 'agent-response-v1' as const,
    semanticVersion: AGENT_RESPONSE_SEMANTIC_VERSION,
    requestId: request.requestId,
    capabilities: {
      message: true,
      question: true,
      error: true,
      blueprints: true,
      patch: 'deferred' as const,
    },
  }

  switch (scenario) {
    case 'message':
      return {
        ...base,
        kind: 'message',
        summary: 'Deterministic mock provider message',
        markdown:
          'This is a deterministic local mock provider response. No network, Tauri command, SecretStore, API key, or document write is required.',
      }
    case 'question':
      return {
        ...base,
        kind: 'question',
        summary: 'Mock provider needs one routing choice',
        question: 'Which rail should the mock Agent panel flow focus on?',
        options: ['VIN', 'VOUT', 'Both'],
      }
    case 'error':
      return {
        ...base,
        kind: 'error',
        summary: 'Deterministic recoverable mock error',
        message: 'Mock provider error: unable to continue without additional circuit constraints.',
        recoverable: true,
      }
    case 'blueprints-invalid':
      return createBlueprintsResponse(base, [createInvalidCandidateDocument()])
    case 'blueprints':
      return createBlueprintsResponse(base, [
        createValidCandidateDocument(request.currentDocument),
        createInvalidCandidateDocument(),
      ])
  }
}

function inferScenario(prompt: string): MockAgentScenario {
  const normalized = prompt.toLowerCase()
  if (normalized.includes('error')) return 'error'
  if (normalized.includes('question') || normalized.includes('ask')) return 'question'
  if (normalized.includes('blueprint') || normalized.includes('candidate') || normalized.includes('alternative')) {
    return normalized.includes('invalid') ? 'blueprints-invalid' : 'blueprints'
  }
  return 'message'
}

function createBlueprintsResponse(
  base: Pick<AgentResponse, 'schemaVersion' | 'semanticVersion' | 'requestId' | 'capabilities'>,
  documents: DocumentFile[],
): AgentResponse {
  return {
    ...base,
    kind: 'blueprints',
    summary: 'Deterministic mock blueprint candidates: valid semantic v4 plus retained invalid draft when requested.',
    blueprints: documents.map((document, index) => {
      const invalid = document.document.id === 'mock-invalid-candidate'
      return {
        title: invalid ? 'Invalid retained candidate' : 'Valid mock candidate',
        summary: invalid
          ? 'Object-shaped semantic v4 draft intentionally containing parser issues.'
          : 'Valid semantic v4 candidate cloned from the current document when provided.',
        rationale: invalid
          ? 'Allows Agent panel validation paths to display candidate issues without dropping the draft.'
          : 'Provides a safe, deterministic candidate for apply/preview flows.',
        tradeoffs: invalid ? ['Requires repair before applying'] : ['Mock data only; not generated by a real provider'],
        highlightedLabels: index === 0 ? ['VIN', 'VOUT'] : ['FLOATING', 'UNUSED_MOCK'],
        notes: invalid ? ['Expected parser issues are part of this fixture.'] : ['Local mock fixture.'],
        document,
        issues: [],
      }
    }),
  }
}

function createValidCandidateDocument(currentDocument?: DocumentFile | null): DocumentFile {
  if (currentDocument) {
    const clone = structuredClone(currentDocument)
    return {
      ...clone,
      document: {
        ...clone.document,
        id: 'mock-valid-candidate',
        title: `${clone.document.title} — mock valid candidate`,
        source: 'ai',
      },
    }
  }

  return {
    schemaVersion: '4.0.0',
    document: {
      id: 'mock-valid-candidate',
      title: 'Mock valid candidate',
      createdAt: '2026-04-26T00:00:00.000Z',
      updatedAt: '2026-04-26T00:00:00.000Z',
      source: 'ai',
      tags: ['mock'],
    },
    devices: [
      {
        id: 'r-mock',
        name: 'Rmock',
        kind: 'resistor',
        terminals: [
          { id: 'r-mock-a', name: 'A', label: 'VIN', direction: 'input' },
          { id: 'r-mock-b', name: 'B', label: 'VOUT', direction: 'output' },
        ],
      },
    ],
    view: {
      canvas: { units: 'px', grid: { enabled: true, size: 16 } },
      devices: { 'r-mock': { position: { x: 80, y: 64 }, shape: 'rectangle' } },
      networkLines: { vin: { label: 'VIN', position: { x: 32, y: 64 } } },
    },
  }
}

function createInvalidCandidateDocument(): DocumentFile {
  return {
    schemaVersion: '4.0.0',
    document: {
      id: 'mock-invalid-candidate',
      title: 'Mock invalid retained candidate',
      createdAt: '2026-04-26T00:00:00.000Z',
      updatedAt: '2026-04-26T00:00:00.000Z',
      source: 'ai',
      tags: ['mock', 'invalid'],
    },
    devices: [
      {
        id: 'u-mock',
        name: 'Umock',
        kind: 'ic',
        terminals: [
          {
            id: 'u-mock-floating',
            name: 'FLOATING',
            label: 'FLOATING',
            direction: 'bidirectional' as 'input',
          },
        ],
      },
    ],
    view: {
      canvas: { units: 'px', grid: { enabled: true, size: 16 } },
      devices: { 'u-mock': { position: { x: 160, y: 96 }, shape: 'rectangle' } },
      networkLines: {
        unusedMock: { label: 'UNUSED_MOCK', position: { x: 200, y: 96 }, orientation: 'horizontal' },
      },
    },
  }
}
